"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()


# Set DEBUG based on the environment
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'
if DEBUG:
    from .local_settings import *
else:
    from .production_settings import *
