# Generated by Django 5.0.4 on 2024-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_court_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlocation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'In Progress'), (4, 'Cancelled')], default=2),
        ),
    ]
