# Generated by Django 5.0.3 on 2024-04-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('YET_TO_BEGIN', 'Yet to Begin'), ('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Cancelled')], default='Yet to Begin', max_length=20),
        ),
    ]
