# Generated by Django 5.0.3 on 2024-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Yet to Begin'), (2, 'Initiated'), (3, 'In Progress'), (4, 'Success'), (5, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='slot',
            name='days',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=10),
        ),
    ]
