# Generated by Django 5.0.3 on 2024-04-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_payment_status_alter_slot_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='days',
        ),
    ]
