# Generated by Django 5.0.3 on 2024-04-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_slot_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled')], default=2),
        ),
    ]
