# Generated by Django 3.2.12 on 2024-03-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='paymeny_status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.slot'),
        ),
    ]
