# Generated by Django 3.2.12 on 2024-03-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20240326_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tax_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
